data:
  dir: '/netscratch/herzig/datasets/BabyCry_no_augment'
  splits: ['train', 'val', 'test']
  spec: False
  augment: 1.0
  rir_dir: '/netscratch/herzig/shared_projects/FAST-RIR/code_new/Generated_RIRs'

model:
  name: 'jdc'
  jdc:
    num_spec: 513
    input_size: 31
    resolution: 16
    figureON: False
    trainable: False
    model_path: 'model/melodyExtraction_JDC/weights/ResNet_joint_add_L(CE_G).hdf5'
  dropout: 0.5
  bi_lstm:
    use: True
    units: 32
  dense: 64
  output: 2

train:
  epochs: 20
  batch_size: 8
  optimizer: 'adam'
  learning_rate: 0.0001
