data:
  dir: /netscratch/herzig/datasets/BabyCry_augment_1
  splits: ['train', 'val', 'test']
  spec: false
  augment: 0.0
  rir_dir: /netscratch/herzig/shared_projects/FAST-RIR/code_new/Generated_RIRs
  mic_dir: /netscratch/herzig/datasets/mic_ir
  mix_up: 1.0
  mix_up_alpha: 0.2
model:
  name: trill
  trill:
    hub_path: https://tfhub.dev/google/trillsson1/1
    trainable: false
  dropout: 0.2
  bi_lstm:
    use: true
    units: 64
  dense: 64
  output: 2
train:
  epochs: 100
  batch_size: 8
  optimizer: adam
  learning_rate: 0.001
  early_stopping: True
