data:
  dir: '/netscratch/herzig/datasets/BabyCry_no_augment'
  splits: ['train', 'val', 'test']
  spec: False
  augment: 1.0
  rir_dir: '/netscratch/herzig/shared_projects/FAST-RIR/code_new/Generated_RIRs'
  mic_dir: '/netscratch/herzig/datasets/mic_ir'
  mix_up: 0.5

model:
  name: 'trill'
  trill: 
    hub_path: 'https://tfhub.dev/google/trillsson1/1'
    trainable: False
  dropout: 0.2
  bi_lstm:
    use: True
    units: 64
  dense: 64
  output: 2

train:
  epochs: 2
  batch_size: 8
  optimizer: 'adam'
  learning_rate: 0.0001
  early_stopping: True