data:
  dir: '/netscratch/herzig/datasets/BabyCry_no_augment'
  splits: ['train', 'val', 'test']
  spec: False

model:
  name: 'jdc'
  jdc:
    num_spec: 513
    input_size: 31
    resolution: 16
    figureON: False
    trainable: False
  dropout: 0.2
  bi_lstm:
    use: False
    units: 64
  dense: 64
  output: 2

train:
  epochs: 100
  batch_size: 8
  optimizer: 'adam'
  learning_rate: 0.0001
